baseURL = 'https://kiyoung-on-ms.github.io/workshop-demo/'
languageCode = 'ko-kr'
defaultContentLanguage = 'ko'
title = 'Microsoft Fabric'
theme = 'relearn'

canonifyURLs = true
relativeURLs = true

[params]
  linkTitle = 'Microsoft Azure'
  disableLandingPageButton = true
  disableGeneratorVersion = true
  disableAssetsBusting = true
  disableRandomIds = true
  
  alwaysopen = false
  collapsibleMenu = true

  custom_css = ["css/menu.css", "css/bar.css"]

  [[params.themeVariant]]
    identifier = 'zen-light'
    name = 'Light'

  [[params.themeVariant]]
    identifier = 'zen-dark'
    name = 'Dark'
  
  [params.author]
    email = 'kiyoungkim@microsoft.com'
    name = 'Kiyoung Kim'

[markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']

[Languages]
  [Languages.ko]
    languageCode = 'ko'
    languageName = '한국어'
    title = 'Microsoft Fabric'
    weight = 1
